[package]
name = "parsing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chromiumoxide = { version = "0.7.0", default-features = false, features = [
    "tokio",
    "tokio-runtime",
] }
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
